export const LAYERS = [
  {id:'data',       col:'#D85A30', label:'01 earth data',           subs:['sensors & platforms','representations','formats — raster','formats — vector','formats — point clouds','formats — tabular & ml','formats — tiling','spatial indexing','embedding types','embedding products','search & retrieval','catalogs']},
  {id:'learning',   col:'#D85A30', label:'02 learning paradigms',   subs:[]},
  {id:'timeline',   col:'#D85A30', label:'03 ai history',           subs:[], _sidebar:true},
  {id:'models',     col:'#D85A30', label:'04 model architectures',  subs:[
    {n:'stat',    idx:0},
    {n:'ai',      idx:1, kids:[
      {n:'classical ml',      idx:3},
      {n:'deep learning',     idx:4},
      {n:'foundation models', idx:5},
      {n:'vlms & llms',       idx:6},
      {n:'agentic',           idx:7},
    ]},
    {n:'physics',  idx:2},
    {n:'by function', idx:8},
  ]},
  {id:'techniques', col:'#D85A30', label:'05 techniques',           subs:['training','adaptation','architecture & fusion','efficiency & compression','evaluation & explainability','metrics']},
  {id:'tasks',      col:'#D85A30', label:'06 tasks / applications',         subs:['geo agi','pixel-level','object-level','scene-level','geometric','3d','temporal','generative','geospatial analysis','preprocessing']},
  {id:'datasets',   col:'#D85A30', label:'07 datasets',             subs:['eo datasets','object detection','segmentation','change detection','vlm / multimodal','benchmarks & challenges']},
  {id:'stack',      col:'#D85A30', label:'08 tools & stack',        subs:['compute platforms','libraries / python','libraries / r','mlops','deployment','spatial dbs','gis tools']},
  {id:'satellites', col:'#D85A30', label:'09 sensors & satellites', subs:['optical & multispectral','sar & radar','hyperspectral','weather & climate','commercial','open missions']},
  {id:'companies',  col:'#D85A30', label:'10 companies',            subs:['satellite providers','drone / aerial','cloud & platforms','geoai startups','open source','open positions']},
  {id:'standards',  col:'#D85A30', label:'11 standards',            subs:['data formats','services','metadata','crs']},
  {id:'roadmap',    col:'#D85A30', label:'12 learning path',        subs:['getting started','courses & moocs','books','tutorials & notebooks','competitions','podcasts','communities']},
  {id:'jobs',       col:'#D85A30', label:'13 job board',            subs:['full-time','part-time & contract','internships & research','remote','by company type','by domain']},
];

export const LAYER_DESC = {
  data:       'The raw material — what sensors capture, how data is stored and indexed, and how it becomes embeddings for ML. From optical and SAR satellites to LiDAR point clouds, cloud-native formats like COG and GeoParquet, H3 spatial indexing, and embedding products like Clay and GeoCLIP.',
  learning:   'How a model learns from data. The choice of paradigm is often the most consequential design decision — supervised needs labels, self-supervised does not, few-shot generalises from minimal examples, and active learning brings humans into the loop strategically.',
  models:     'Three paradigms for modelling Earth: statistical methods (kriging, Gaussian processes, Bayesian inference), AI/ML from classical random forests through transformer foundation models and agentic pipelines, and physics-based approaches like radiative transfer and hydrological models. Most production systems combine all three.',
  techniques: 'The methods that make models work — how to train them, adapt them to new sensors or geographies, fuse multimodal inputs, compress them for edge deployment, and evaluate them with the right metrics for each task.',
  tasks:      'What you are building, grouped by the Sat2Info / Data2Sat / Sat2Model / Sat2Sat framework. Ranges from pixel-level segmentation and object detection, through scene understanding and geolocalization, to 3D reconstruction, temporal change detection, and generative synthesis.',
  datasets:   'The training data and benchmarks the field has standardised around — EO datasets from Sentinel and Landsat, object detection suites like DOTA and xView, segmentation benchmarks, change detection datasets, VLM evaluation suites, and the major competitions that track state of the art.',
  stack:      'The tools and infrastructure for running geospatial AI — compute platforms, Python and R libraries, MLOps tooling, model deployment frameworks, spatial databases and vector stores, and GIS visualisation tools.',
  companies:  'The organisations that make up the geospatial AI ecosystem — satellite data providers, drone manufacturers, cloud and compute platforms, GeoAI startups, and the open source community. The linked GitHub repo tracks 6,573+ companies in this space.',
  standards:  'The interoperability layer that lets geospatial data move between tools — cloud-native formats (COG, STAC, GeoParquet), OGC service protocols (WMS / WFS / OGC API), metadata schemas (ISO 19115, INSPIRE), and coordinate reference systems.',
  satellites: 'The orbital infrastructure feeding geospatial AI — from free open missions like Sentinel and Landsat through commercial high-resolution optical and SAR constellations to hyperspectral and weather satellites. Knowing what each sensor provides, at what resolution and revisit, is the first decision in any EO pipeline.',
  roadmap:    'A curated path through the field — from first principles to research-level mastery. Covers structured courses and MOOCs, essential books, hands-on tutorials and notebooks, competitions to test your skills, and communities where the work happens.',
  jobs:       'Open roles across the geospatial AI industry — full-time positions, contracts, internships, and research roles at satellite companies, GeoAI startups, cloud platforms, and research institutions. Updated by the community.',
};

export const TERM_DESC = {
  data:       'sensors, formats, embeddings & catalogs',
  learning:   'model learning — supervised to zero-shot',
  models:     'statistical · AI/ML · physics-based models',
  techniques: 'training, adaptation, efficiency & metrics',
  tasks:      'the full geo task spectrum (Sat2Info → Sat2Sat)',
  datasets:   'training datasets and benchmarks',
  stack:      'compute, libraries, MLOps, deployment & DBs',
  companies:  'the geospatial AI ecosystem',
  standards:  'data formats, services & CRS',
  satellites: 'optical · SAR · hyperspectral · weather constellations',
  roadmap:    'courses, books, tutorials & communities',
  jobs:       'open roles across the geospatial AI industry',
  timeline:   'ml architecture timeline — always visible on the right →',
};
